### ISSUE TITLE
视频的C3D特征和idt特征

### ISSUE THREAD

**Issue by success-path698** [YangLiu9208/DIVAFN#1]
您好，您在DIVAFN的下载文件中只放了ucf101中两个视频的c3d运行结果。您能把所有需要用到的视频的c3d特征和idts特征的运行结果发我吗？我这边因为设备原因，没办法提取视频的c3d特征以及idts+llc特征。您有备份吗？有留的话，请邮箱发给我吧。
另外，您实验中hmdb51数据集下的视频没有全部使用把，只使用与ead数据集十五类相对应的视频吧？期待并感谢您的回复

**Comment by YangLiu9208** [comment]
非常感谢您的关注，所有的特征文件非常大，好几百G，我这边可能没有备份。C3D在一般的显卡环境就可以运行，不是很耗费显卡资源。您可以尝试自己提取。HMDB51只采用了十五类对应的视频。

**Comment by success-path698** [comment]
好的，谢谢
